spring.application.name=skillverse-v2
spring.datasource.url=jdbc:postgresql://localhost:5332/skillverse-v2
spring.datasource.username=dhanika
spring.datasource.password=Dhanika_22
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true